package com.maisonneuve.tp2_algorithme_spotify.model;

public enum Genre {

    A_CAPPELLA("a cappella"),
    ACOUSTIC_COVER("acoustic cover"),
    ADELAIDE_PUNK("adelaide punk"),
    AFROBEATS("afrobeats"),
    ALABAMA_RAP("alabama rap"),
    ALBUM_ROCK("album rock"),
    ALT_Z("alt z"),
    ALTERNATIVE_METAL("alternative metal"),
    ALTERNATIVE_ROCK("alternative rock"),
    AMERICAN_FOLK_REVIVAL("american folk revival"),
    ANARCHO_PUNK("anarcho-punk"),
    ATLANTA_BASS("atlanta bass"),
    AUSSIETRONICA("aussietronica"),
    AUSTRALIAN_ALTERNATIVE_POP("australian alternative pop"),
    AUSTRALIAN_ALTERNATIVE_ROCK("australian alternative rock"),
    AUSTRALIAN_COMEDY("australian comedy"),
    AUSTRALIAN_COUNTRY("australian country"),
    AUSTRALIAN_DANCE("australian dance"),
    AUSTRALIAN_ELECTROPOP("australian electropop"),
    AUSTRALIAN_HIP_HOP("australian hip hop"),
    AUSTRALIAN_INDIE("australian indie"),
    AUSTRALIAN_INDIE_FOLK("australian indie folk"),
    AUSTRALIAN_INDIE_ROCK("australian indie rock"),
    AUSTRALIAN_INDIGENOUS_MUSIC("australian indigenous music"),
    AUSTRALIAN_POP("australian pop"),
    AUSTRALIAN_R_B("australian r&b"),
    AUSTRALIAN_REGGAE_FUSION("australian reggae fusion"),
    AUSTRALIAN_ROCK("australian rock"),
    AUSTRALIAN_SINGER_SONGWRITER("australian singer-songwriter"),
    AUSTRALIAN_SKA("australian ska"),
    AUSTRALIAN_TALENT_SHOW("australian talent show"),
    BAHAMIAN_POP("bahamian pop"),
    BALKAN_BEATS("balkan beats"),
    BANJO("banjo"),
    BEATLESQUE("beatlesque"),
    BEDROOM_POP("bedroom pop"),
    BOUNCY_HOUSE("bouncy house"),
    BOY_BAND("boy band"),
    BRILL_BUILDING_POP("brill building pop"),
    BRIT_FUNK("brit funk"),
    BRITCORE("britcore"),
    BRITISH_ALTERNATIVE_ROCK("british alternative rock"),
    BRITISH_BLUES("british blues"),
    BRITISH_COMEDY("british comedy"),
    BRITISH_FOLK("british folk"),
    BRITISH_INVASION("british invasion"),
    BRITISH_SOUL("british soul"),
    BRITPOP("britpop"),
    BRONX_HIP_HOP("bronx hip hop"),
    BROOKLYN_INDIE("brooklyn indie"),
    BUBBLE_TRANCE("bubble trance"),
    BUBBLEGUM_DANCE("bubblegum dance"),
    BUBBLEGUM_POP("bubblegum pop"),
    BUSH_BALLAD("bush ballad"),
    CALYPSO("calypso"),
    CANADIAN_COUNTRY("canadian country"),
    CANADIAN_HIP_HOP("canadian hip hop"),
    CANADIAN_POP("canadian pop"),
    CANADIAN_POP_PUNK("canadian pop punk"),
    CANADIAN_ROCK("canadian rock"),
    CANDY_POP("candy pop"),
    CARTOON("cartoon"),
    CHICAGO_SOUL("chicago soul"),
    CHRISTIAN_MUSIC("christian music"),
    CLASSIC_AUSTRALIAN_COUNTRY("classic australian country"),
    CLASSIC_BELGIAN_POP("classic belgian pop"),
    CLASSIC_CANADIAN_ROCK("classic canadian rock"),
    CLASSIC_COUNTRY_POP("classic country pop"),
    CLASSIC_GARAGE_ROCK("classic garage rock"),
    CLASSIC_GIRL_GROUP("classic girl group"),
    CLASSIC_HOUSE("classic house"),
    CLASSIC_NZ_POP("classic nz pop"),
    CLASSIC_ROCK("classic rock"),
    CLASSIC_SOUL("classic soul"),
    CLASSIC_UK_POP("classic uk pop"),
    COLLAGE_POP("collage pop"),
    COMEDY_RAP("comedy rap"),
    COMIC("comic"),
    CONTEMPORARY_COUNTRY("contemporary country"),
    CONTEMPORARY_R_B("contemporary r&b"),
    COSMIC_AMERICAN("cosmic american"),
    COUNTRY_GOSPEL("country gospel"),
    COUNTRY_POP("country pop"),
    COUNTRY_ROCK("country rock"),
    COWBOY_WESTERN("cowboy western"),
    DANCE_POP("dance pop"),
    DANCE_ROCK("dance rock"),
    DANISH_POP("danish pop"),
    DANSKTOP("dansktop"),
    DEEP_ADULT_STANDARDS("deep adult standards"),
    DEEP_EURODANCE("deep eurodance"),
    DEEP_SOFT_ROCK("deep soft rock"),
    DEEP_TALENT_SHOW("deep talent show"),
    DEEP_TROPICAL_HOUSE("deep tropical house"),
    DERBY_INDIE("derby indie"),
    DISCO("disco"),
    DISCO_HOUSE("disco house"),
    DIVA_HOUSE("diva house"),
    DOO_WOP("doo-wop"),
    DOUBLE_DRUMMING("double drumming"),
    DREAM_POP("dream pop"),
    DUTCH_POP("dutch pop"),
    EARLY_REGGAE("early reggae"),
    EASY_LISTENING("easy listening"),
    EDM("edm"),
    ELECTRO_HOUSE("electro house"),
    ELECTRO_JAZZ("electro jazz"),
    ELECTRO_SWING("electro swing"),
    ELECTRONIC_ROCK("electronic rock"),
    ELECTROPOP("electropop"),
    ENKA("enka"),
    EURODANCE("eurodance"),
    EUROPOP("europop"),
    FILTER_HOUSE("filter house"),
    FLAMENCO_ELECTRONICA("flamenco electronica"),
    FOLK_ROCK("folk rock"),
    FOLK_POP("folk-pop"),
    FOOTBALL("football"),
    FREESTYLE("freestyle"),
    FRENCH_INDIE_POP("french indie pop"),
    FUNANA("funana"),
    GAUZE_POP("gauze pop"),
    GERMAN_POP("german pop"),
    GERMAN_POP_ROCK("german pop rock"),
    GERMAN_SHOW_TUNES("german show tunes"),
    GERMAN_TECHNO("german techno"),
    GIRL_GROUP("girl group"),
    GLAM_METAL("glam metal"),
    GLAM_ROCK("glam rock"),
    HAMMOND_ORGAN("hammond organ"),
    HARD_ROCK("hard rock"),
    HAWAIIAN("hawaiian"),
    HEARTLAND_ROCK("heartland rock"),
    HI_NRG("hi-nrg"),
    HIP_HOUSE("hip house"),
    HMONG_POP("hmong pop"),
    HYPERTECHNO("hypertechno"),
    IDOL("idol"),
    INDIE_POP_RAP("indie pop rap"),
    INDIE_POPTIMISM("indie poptimism"),
    INDIE_R_B("indie r&b"),
    INDIE_SALVADORENO("indie salvadoreno"),
    INSTRUMENTAL_WORSHIP("instrumental worship"),
    IRISH_COUNTRY("irish country"),
    IRISH_POP("irish pop"),
    ISRAELI_POP("israeli pop"),
    ITALIAN_TRANCE("italian trance"),
    JAMAICAN_SKA("jamaican ska"),
    JANGLE_POP("jangle pop"),
    K_POP("k-pop"),
    K_POP_GIRL_GROUP("k-pop girl group"),
    KARAOKE("karaoke"),
    LATIN_POP("latin pop"),
    LGBTQ_HIP_HOP("lgbtq+ hip hop"),
    LIBRARY_MUSIC("library music"),
    LILITH("lilith"),
    LONDON_RAP("london rap"),
    MANCHESTER_INDIE("manchester indie"),
    MELBOURNE_BOUNCE("melbourne bounce"),
    MELLOW_GOLD("mellow gold"),
    MELODIC_RAP("melodic rap"),
    MERSEYBEAT("merseybeat"),
    MIAMI_BASS("miami bass"),
    MIAMI_HIP_HOP("miami hip hop"),
    MILITARY_CADENCE("military cadence"),
    MOD_REVIVAL("mod revival"),
    MODERN_ALTERNATIVE_ROCK("modern alternative rock"),
    MODERN_BLUES_ROCK("modern blues rock"),
    MODERN_FOLK_ROCK("modern folk rock"),
    MODERN_ROCK("modern rock"),
    MUSICAL_ADVOCACY("musical advocacy"),
    NASHVILLE_SOUND("nashville sound"),
    NEDERPOP("nederpop"),
    NEO_MELLOW("neo mellow"),
    NEO_SOUL("neo soul"),
    NEO_TRADITIONAL_COUNTRY("neo-traditional country"),
    NEW_JACK_SWING("new jack swing"),
    NEW_ORLEANS_SOUL("new orleans soul"),
    NEW_WAVE("new wave"),
    NEW_WAVE_POP("new wave pop"),
    NORTHERN_IRISH_PUNK("northern irish punk"),
    NORTHERN_SOUL("northern soul"),
    NOVELTY("novelty"),
    NU_METAL("nu metal"),
    NYC_POP("nyc pop"),
    NYC_RAP("nyc rap"),
    NZ_FOLK("nz folk"),
    NZ_HIP_HOP("nz hip hop"),
    NZ_POP("nz pop"),
    NZ_REGGAE("nz reggae"),
    OLD_SCHOOL_HIP_HOP("old school hip hop"),
    OPERATIC_POP("operatic pop"),
    OPM("opm"),
    PARODY("parody"),
    PHILLY_INDIE("philly indie"),
    PHILLY_SOUL("philly soul"),
    POP("pop"),
    POP_DANCE("pop dance"),
    POP_EDM("pop edm"),
    POP_R_B("pop r&b"),
    POP_ROCK("pop rock"),
    POP_SOUL("pop soul"),
    POP_VIOLIN("pop violin"),
    PORTLAND_INDIE("portland indie"),
    POST_DISCO("post-disco"),
    POST_GRUNGE("post-grunge"),
    POV_INDIE("pov: indie"),
    POWER_POP("power pop"),
    PROTOPUNK("protopunk"),
    PSYCHEDELIC_BLUES_ROCK("psychedelic blues-rock"),
    PSYCHEDELIC_FOLK_ROCK("psychedelic folk rock"),
    PSYCHEDELIC_ROCK("psychedelic rock"),
    PUB_ROCK("pub rock"),
    R_B("r&b"),
    RAP_KREYOL("rap kreyol"),
    REGGAE_FUSION("reggae fusion"),
    REMIX_PRODUCT("remix product"),
    RHYTHM_AND_BLUES("rhythm and blues"),
    ROCK_KEYBOARD("rock keyboard"),
    ROCK_PROGRESSIF_FRANCAIS("rock progressif francais"),
    ROCK_AND_ROLL("rock-and-roll"),
    ROCKABILLY("rockabilly"),
    ROMANIAN_POP("romanian pop"),
    ROOTS_ROCK("roots rock"),
    RUTA_DESTROY("ruta destroy"),
    SCOTTISH_NEW_WAVE("scottish new wave"),
    SINGER_SONGWRITER_POP("singer-songwriter pop"),
    SMOOTH_JAZZ("smooth jazz"),
    SOCIAL_MEDIA_POP("social media pop"),
    SOFT_ROCK("soft rock"),
    SOLO_WAVE("solo wave"),
    SOUL("soul"),
    SOULDIES("souldies"),
    SOUTHERN_ROCK("southern rock"),
    SOUTHERN_SOUL("southern soul"),
    SPANISH_INVASION("spanish invasion"),
    STOMP_AND_HOLLER("stomp and holler"),
    SUNSHINE_POP("sunshine pop"),
    SURF_MUSIC("surf music"),
    SWAMP_POP("swamp pop"),
    SWEDISH_INDIE_ROCK("swedish indie rock"),
    SWEDISH_JAZZ("swedish jazz"),
    SWING_ITALIANO("swing italiano"),
    TALENT_SHOW("talent show"),
    THEME("theme"),
    TRADITIONAL_COUNTRY("traditional country"),
    TRAP_QUEEN("trap queen"),
    TROPICAL("tropical"),
    UK_ALTERNATIVE_POP("uk alternative pop"),
    UK_DANCE("uk dance"),
    UK_GARAGE("uk garage"),
    UK_HIP_HOP("uk hip hop"),
    UK_POP("uk pop"),
    UK_REGGAE("uk reggae"),
    VINTAGE_FRENCH_ELECTRONIC("vintage french electronic"),
    VIRAL_POP("viral pop"),
    VIRAL_TRAP("viral trap"),
    VOLKSMUSIK("volksmusik"),
    YACHT_ROCK("yacht rock"),
    YODELING("yodeling"),
    ZOLO("zolo"),
    ZOUK("zouk");

    private final String nomBrut;
    private final String nomFormate;

    Genre(String nomBrut) {
        this.nomBrut = nomBrut;
        this.nomFormate = formaterNom(nomBrut);

    }

    private static String formaterNom(String texte) {
        if (texte == null || texte.isBlank()) {
            return "";
        }

        String[] mots = texte.split(" ");
        StringBuilder sb = new StringBuilder();

        for (String mot : mots) {
            if (!mot.isEmpty()) {
                sb.append(Character.toUpperCase(mot.charAt(0)))
                        .append(mot.substring(1).toLowerCase())
                        .append(" ");
            }
        }

        return sb.toString().trim();
    }

    public String getNomBrut() {
        return nomBrut;
    }

    public String getNomFormate() {
        return nomFormate;
    }

    @Override
    public String toString() {
        return nomFormate;
    }
}
